/**
 * Co-determination document sets for Austria, the Netherlands, Sweden and
 * France — and India's employee-monitoring position.
 *
 * These five presets previously existed with the right *settings* but borrowed
 * Germany's Betriebsvereinbarung or a generic consultation pack for their
 * paperwork. That is a real gap, not a cosmetic one: a Dutch OR does not want a
 * German works agreement, it wants an Article 27 WOR instemmingsverzoek; a
 * Swedish union expects an MBL §11 kallelse; a French CSE expects a note
 * d'information with the CNIL's proportionality analysis in it. Handing over
 * the wrong instrument is how a six-week approval becomes an eighteen-month
 * one, which is the exact failure this product is sold to prevent.
 *
 * Each document is a first draft in the working language of the body that will
 * read it, generated from the live configuration. None of it is legal advice,
 * and every document says so in its own language.
 */

const DE_DISCLAIMER = '\n\n---\n*Von Vault aus Ihrer aktiven Konfiguration erzeugt. Erster Entwurf zur Prüfung und Anpassung durch Ihre Datenschutzbeauftragte, den Betriebsrat oder Ihre Rechtsberatung — keine Rechtsberatung.*\n';
const NL_DISCLAIMER = '\n\n---\n*Door Vault gegenereerd op basis van uw actieve configuratie. Dit is een eerste concept ter beoordeling door uw FG, de ondernemingsraad of uw juridisch adviseur — het is geen juridisch advies.*\n';
const SE_DISCLAIMER = '\n\n---\n*Genererat av Vault utifrån er aktiva konfiguration. Detta är ett första utkast för granskning av ert dataskyddsombud, facket eller er juridiska rådgivare — det är inte juridisk rådgivning.*\n';
const FR_DISCLAIMER = '\n\n---\n*Généré par Vault à partir de votre configuration active. Il s\'agit d\'un premier projet destiné à être examiné par votre DPO, le CSE ou votre conseil juridique — ce n\'est pas un avis juridique.*\n';
const EN_DISCLAIMER = '\n\n---\n*Generated by Vault from your live configuration. This is a first draft for your DPO, works council or counsel to review and adapt — it is not legal advice.*\n';

const list = (xs, fallback = '—') => ((xs || []).length ? xs.join(', ') : fallback);

// ---------------------------------------------------------------------------
// 🇦🇹 AUSTRIA — §96(1) Z3 and §96a ArbVG
//
// Austria's regime is stricter than Germany's in one specific way people miss:
// §96(1) Z3 covers systems that touch human dignity ("die Menschenwürde
// berühren") and a works agreement is a *precondition of lawfulness* — without
// it the system may not be introduced at all, and the Betriebsrat cannot be
// overruled by the Einigungsstelle the way it can in Germany. §96a covers
// systems that merely process personal data, where arbitration IS available.
// Which paragraph applies decides whether the council holds a veto, so the
// document says which one Vault falls under and why.
// ---------------------------------------------------------------------------

export function atBetriebsvereinbarung({ settings, generatedAt }) {
  return `# Betriebsvereinbarung über den Einsatz von Vault (KI-Gedächtnis-Governance)
**Entwurf — Stand ${generatedAt}**
**Rechtsgrundlage:** § 96 Abs. 1 Z 3 ArbVG (zustimmungspflichtig) bzw. § 96a Abs. 1 Z 1 ArbVG

Abgeschlossen zwischen dem Betriebsinhaber und dem Betriebsrat gemäß § 29 ArbVG.

## Vorbemerkung: welche Bestimmung anwendbar ist
§ 96 Abs. 1 Z 3 ArbVG erfasst Kontrollmaßnahmen und technische Systeme, **die die Menschenwürde berühren**. Für diese
ist die Zustimmung des Betriebsrats **zwingende Wirksamkeitsvoraussetzung**; sie kann **nicht** durch die
Schlichtungsstelle ersetzt werden. § 96a Abs. 1 Z 1 ArbVG erfasst Systeme zur automationsunterstützten Ermittlung
personenbezogener Daten, die über die Angabe allgemeiner Angaben zur Person und fachlichen Voraussetzungen hinausgehen;
hier ist eine Ersetzung durch die Schlichtungsstelle möglich.

**Einschätzung der Parteien:** Vault erhebt keine Leistungs- oder Verhaltensdaten, führt keine Bewertung von Personen
durch und stellt keine individuellen Auswertungen bereit (§ 4 dieser Vereinbarung). Die Parteien behandeln die
Vereinbarung dennoch **vorsorglich als solche nach § 96 Abs. 1 Z 3**, weil die Zuordnung im Streitfall vom Gericht
vorgenommen wird und die strengere Einordnung die Beschäftigten besserstellt.

## § 1 Gegenstand und Zweck
Vault dient ausschließlich der Governance des gemeinsamen KI-Gedächtnisses: der Abwehr manipulierter Inhalte
(Prompt Injection, Memory Poisoning), der Nachvollziehbarkeit dessen, was ein KI-System zu einem Zeitpunkt für wahr
gehalten hat, und der Erfüllung gesetzlicher Aufbewahrungspflichten.
**Eine Verhaltens- oder Leistungskontrolle ist ausgeschlossen und technisch nicht vorgesehen.**

## § 2 Erfassungsumfang
(1) Erfasst werden Interaktionen mit betrieblichen KI-Systemen ${settings.sampleDontStream ? `ereignisbasiert und stichprobenartig (Stichprobenquote ${Math.round((settings.sampleRate ?? 0.05) * 100)} %)` : 'laufend'}.
(2) **Nicht erfasst werden:** ${list(settings.excludedContexts)}.
(3) Die Erfassung erfolgt ${settings.workingHoursOnly ? 'ausschließlich innerhalb der Normalarbeitszeit im Sinne des AZG' : 'ohne Zeitbeschränkung'}.
(4) Eine verdeckte Erfassung findet nicht statt; die entsprechende Funktion existiert im System nicht.

## § 3 Pseudonymisierung und Re-Identifizierung
(1) Beschäftigtenbezogene Daten werden standardmäßig pseudonymisiert.
(2) Eine Re-Identifizierung ist nur bei dokumentiertem rechtlichem Grund zulässig, bedarf der Zustimmung **zweier
    namentlich benannter Personen**, ist zeitlich befristet, wird protokolliert und dem Betriebsrat **unverzüglich**
    berichtet.
(3) Der Betriebsrat erhält quartalsweise eine vollständige Liste aller Re-Identifizierungen — auch wenn diese null ist.

## § 4 Auswertungen
(1) Auswertungen erfolgen ausschließlich aggregiert mit einer Mindestgruppengröße von **k = ${settings.kAnonymityFloor ?? 5}**.
    Unterhalb dieser Schwelle wird kein Wert angezeigt, auch nicht gerundet oder als Bandbreite.
(2) **Individuelle Leistungs- oder Verhaltensauswertungen sind im System nicht vorhanden.** Dies ist keine
    Konfigurationseinstellung, sondern eine Eigenschaft der Software.

## § 5 Ausgeschlossene Verwendungen
Ausgeschlossen sind insbesondere: Leistungs- und Verhaltenskontrolle, Produktivitäts- oder Aktivitätsmessung,
Emotions-, Stimmungs-, Stress-, Engagement- oder Ehrlichkeitsanalyse (auch unzulässig nach Art. 5 Abs. 1 lit. f
KI-VO), verdeckte Überwachung, Standortverfolgung sowie jede Verwendung als Grundlage personalrechtlicher Maßnahmen.

## § 6 Aufbewahrung
Beschäftigtenbezogene Daten werden nach **${settings.employeeRetention ?? '3 Monaten'}** gelöscht, soweit keine
gesetzliche Aufbewahrungspflicht (z. B. § 132 BAO, § 212 UGB) entgegensteht. Kollisionen werden dokumentiert,
begründet und dem Betriebsrat offengelegt.

## § 7 Rechte der Beschäftigten
Einsicht, Export, Berichtigung und förmlicher Widerspruch über das Portal „Meine Daten"; Widersprüche werden
nachverfolgt und beantwortet. Die Rechte nach Art. 15–22 DSGVO bleiben unberührt.

## § 8 Beteiligung des Betriebsrats
(1) Der Betriebsrat erhält eine eigene **Nur-Lese-Rolle** mit Einsicht in Konfiguration, Aufbewahrungsfristen,
    Zugriffsmatrix und sämtliche Re-Identifizierungen.
(2) Jede Änderung überwachungsrelevanter Einstellungen wird dem Betriebsrat **automatisch angezeigt** und bedarf
    seiner Zustimmung; bis zur Zustimmung bleibt die bisherige Einstellung wirksam.

## § 9 Streitigkeiten
Für Angelegenheiten nach § 96a ArbVG entscheidet im Streitfall die **Schlichtungsstelle** (§ 144 ArbVG). Für
Angelegenheiten nach § 96 Abs. 1 Z 3 ArbVG besteht **kein Ersetzungsverfahren**; ohne Zustimmung des Betriebsrats
unterbleibt der Einsatz.

## § 10 Inkrafttreten, Laufzeit, Nachwirkung
Diese Vereinbarung tritt mit Unterzeichnung in Kraft. Sie kann von beiden Seiten unter Einhaltung einer Frist von
drei Monaten gekündigt werden. **Eine Nachwirkung nach § 32 Abs. 3 ArbVG wird ausdrücklich ausgeschlossen**; mit
Wirksamwerden der Kündigung wird die Verarbeitung beschäftigtenbezogener Daten eingestellt.

_____________________          _____________________
Betriebsinhaber                Betriebsrat${DE_DISCLAIMER}`;
}

export function atDsgAssessment({ settings, generatedAt }) {
  return `# Datenschutzrechtliche Beurteilung (DSG i.V.m. DSGVO)
**Stand:** ${generatedAt}
**Verantwortlicher:** [Firma], [Anschrift] · **Datenschutzbeauftragte:** [Name]

## 1. Verarbeitungszweck
Governance des gemeinsamen KI-Gedächtnisses: Integrität, Nachvollziehbarkeit, Erfüllung von Aufbewahrungspflichten.

## 2. Rechtsgrundlage
Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an Richtigkeit und Sicherheit betrieblicher KI-Systeme), ergänzt
durch die Betriebsvereinbarung nach § 96 Abs. 1 Z 3 ArbVG. Eine Einwilligung wird **nicht** herangezogen: im
Beschäftigungsverhältnis ist sie regelmäßig nicht freiwillig.

## 3. Verhältnismäßigkeit
**Geeignetheit.** Ohne Kontrolle kann jeder von einem Agenten gelesene Inhalt zu einer dauerhaften, vertrauenswürdigen
Aussage werden. Die Prüfkette verhindert dies nachweisbar.
**Erforderlichkeit.** Gelindere Mittel (bloße Protokollierung ohne Prüfung, rein organisatorische Weisungen) erreichen
den Zweck nicht, weil sie die Übernahme falscher Inhalte nicht verhindern, sondern nur nachträglich dokumentieren.
**Angemessenheit.** ${settings.sampleDontStream ? 'Stichprobenartige' : 'Laufende'} Erfassung,
Pseudonymisierung als Standard, k = ${settings.kAnonymityFloor ?? 5}, Ausschluss von
${list(settings.excludedContexts)}, Löschung nach ${settings.employeeRetention ?? '3 Monaten'}, keine
Individualauswertung.

## 4. Betroffenenrechte
Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch — jeweils über „Meine Daten" und über die
Datenschutzbeauftragte. Kein automatisiertes Entscheiden im Sinne des Art. 22 DSGVO.

## 5. Datensicherheit
Verschlüsselung im Ruhezustand und bei der Übertragung, kundenseitig gehaltene Signaturschlüssel,
manipulationssicheres Ereignisprotokoll, rollenbasierte Zugriffsteuerung, Vier-Augen-Prinzip bei Re-Identifizierung.

## 6. Ergebnis
Die Verarbeitung ist bei Einhaltung der Betriebsvereinbarung zulässig. Eine Datenschutz-Folgenabschätzung nach
Art. 35 DSGVO wird ${settings.aggregateOnly ? 'vorsorglich' : ''} durchgeführt und liegt gesondert vor.${DE_DISCLAIMER}`;
}

// ---------------------------------------------------------------------------
// 🇳🇱 NETHERLANDS — Article 27 WOR
//
// The Dutch instrument is *instemming* (consent), not advice: without OR consent
// the decision is voidable (nietig) if the OR invokes nullity in writing within
// one month. The document therefore has to be a consent REQUEST with the six
// things Article 27(2) requires, and it has to name the nullity clock, because
// an employer who does not know about that clock is an employer who will be
// surprised by it.
// ---------------------------------------------------------------------------

export function nlInstemmingsverzoek({ settings, generatedAt }) {
  return `# Instemmingsverzoek ex artikel 27 WOR
**Aan:** de ondernemingsraad · **Van:** de bestuurder · **Datum:** ${generatedAt}
**Betreft:** voorgenomen besluit tot invoering van Vault (governance van het gedeelde AI-geheugen)

## 1. Grondslag van dit verzoek
Artikel 27 lid 1 sub k en sub l WOR: een voorgenomen besluit tot vaststelling of wijziging van een regeling omtrent
**het verwerken van persoonsgegevens van in de onderneming werkzame personen** en van **voorzieningen die gericht zijn
op of geschikt zijn voor waarneming van of controle op aanwezigheid, gedrag of prestaties**.

De bestuurder verzoekt om instemming. Zonder instemming — of zonder vervangende toestemming van de kantonrechter
(artikel 27 lid 4 WOR) — wordt het besluit niet uitgevoerd. De ondernemingsraad kan de nietigheid van een zonder
instemming genomen besluit inroepen **binnen één maand** nadat hem is gebleken dat het besluit is genomen
(artikel 27 lid 5 WOR).

## 2. Beweegredenen (art. 27 lid 2)
AI-agents lezen uit en schrijven naar een gedeeld geheugen. Zonder controle kan elke inhoud die een agent tegenkomt
een blijvend, vertrouwd "feit" worden — ook wanneer die inhoud afkomstig is van een e-mail van buiten, een geplakt
document of een geslaagde prompt-injectie. Vault beoordeelt elke kandidaat-inhoud voordat deze onthouden wordt, en legt
vast wat wanneer geloofd werd.

## 3. Gevolgen voor de in de onderneming werkzame personen (art. 27 lid 2)
| Onderwerp | Invulling |
|---|---|
| Wat wordt vastgelegd | Interacties met bedrijfs-AI-systemen, ${settings.sampleDontStream ? `steekproefsgewijs (${Math.round((settings.sampleRate ?? 0.05) * 100)} %) en op gebeurtenis` : 'doorlopend'} |
| Wat uitdrukkelijk niet | ${list(settings.excludedContexts)} |
| Tijdvenster | ${settings.workingHoursOnly ? 'uitsluitend tijdens werktijd' : 'geen tijdsbeperking'} |
| Pseudonimisering | ${settings.pseudonymiseByDefault ? 'standaard aan' : 'uit'} |
| Individuele rapportages | ${settings.noIndividualDashboards ? 'bestaan niet in het systeem' : 'beschikbaar'} |
| Minimale groepsgrootte | k = ${settings.kAnonymityFloor ?? 5} |
| Bewaartermijn | ${settings.employeeRetention ?? 'standaardtermijn'} |
| Beoordeling van prestaties | uitgesloten; de functionaliteit ontbreekt |

## 4. Wat het systeem uitdrukkelijk **niet** kan
Prestatie- of productiviteitsmeting · emotie-, stemmings-, stress- of betrokkenheidsanalyse (tevens verboden op grond
van artikel 5 lid 1 onder f AI-verordening) · heimelijke waarneming · gebruik als grondslag voor arbeidsrechtelijke
maatregelen · individuele dashboards, ook niet voor HR en ook niet via noodtoegang.

## 5. Rechten van werknemers
Inzage, export, rectificatie en formeel bezwaar via het portaal "Mijn gegevens". Bezwaren worden geregistreerd en
beantwoord. De rechten uit de AVG blijven onverkort gelden; de FG is bereikbaar via [contact].

## 6. Toezicht door de ondernemingsraad
De OR krijgt een eigen leesrol met inzicht in de configuratie, de bewaartermijnen, de toegangsmatrix en **elke
her-identificatie**. Wijzigingen in monitoring-relevante instellingen worden automatisch aan de OR gemeld en vergen
opnieuw instemming.

## 7. Voorgenomen tijdpad
| Stap | Termijn |
|---|---|
| Overlegvergadering (art. 27 lid 3) | ten minste éénmaal, vóór besluitvorming |
| Schriftelijke reactie van de OR | in onderling overleg te bepalen |
| Besluit en uitvoering | uitsluitend na verkregen instemming |
| Evaluatie met de OR | 6 en 12 maanden na invoering |

## 8. Bijlagen
1. DPIA (artikel 35 AVG), gegenereerd uit de actieve configuratie
2. Overzicht van uitgesloten contexten en bewaartermijnen
3. Toegangsmatrix per rol
4. Verwerkersovereenkomst met de leverancier${NL_DISCLAIMER}`;
}

export function nlDpiaAddendum({ settings, generatedAt }) {
  return `# DPIA-addendum — proportionaliteit en subsidiariteit (AP-toetsingskader)
**Datum:** ${generatedAt}

De Autoriteit Persoonsgegevens toetst werknemersmonitoring aan **noodzaak, proportionaliteit, subsidiariteit** en
**transparantie**. Dit addendum beantwoordt die vier vragen expliciet.

**Noodzaak.** Het gerechtvaardigd belang is de integriteit van het gedeelde AI-geheugen. Zonder poortwachter wordt
elke gelezen inhoud potentieel een blijvend feit; dat is aantoonbaar misbruikt via prompt-injectie.

**Proportionaliteit.** De inbreuk is beperkt tot ${settings.sampleDontStream ? 'steekproeven' : 'volledige vastlegging'} van
interacties met bedrijfs-AI-systemen, gepseudonimiseerd, ${settings.workingHoursOnly ? 'binnen werktijd' : 'zonder tijdsbeperking'},
met uitsluiting van ${list(settings.excludedContexts)} en een minimale groepsgrootte van k = ${settings.kAnonymityFloor ?? 5}.

**Subsidiariteit.** Minder ingrijpende alternatieven — enkel loggen zonder beoordeling, of uitsluitend
gedragsinstructies aan medewerkers — bereiken het doel niet: zij registreren de fout achteraf in plaats van hem te
voorkomen. Dit is schriftelijk afgewogen en vastgelegd.

**Transparantie.** Elke medewerker ziet via "Mijn gegevens" wat is vastgelegd, en kan bezwaar maken. De OR heeft
doorlopend inzage.

**Restrisico.** ${settings.noIndividualDashboards ? 'Laag: individuele beoordeling is technisch afwezig.' : 'Verhoogd: individuele weergaven zijn beschikbaar — heroverweeg deze instelling.'}${NL_DISCLAIMER}`;
}

// ---------------------------------------------------------------------------
// 🇸🇪 SWEDEN — MBL §§ 11, 19 and the union's veto-free but blocking negotiation
//
// Sweden's mechanism is not consent and not co-decision: it is a *duty to
// negotiate before deciding* (primär förhandlingsskyldighet). The employer
// ultimately decides, but deciding before negotiating is itself the breach, and
// it carries allmänt skadestånd. The document is therefore a negotiation
// summons plus the §19 information the union is owed, not a consent request.
// ---------------------------------------------------------------------------

export function seMblForhandling({ settings, generatedAt }) {
  return `# Kallelse till förhandling enligt 11 § MBL
**Till:** [facklig organisation] · **Från:** [arbetsgivare] · **Datum:** ${generatedAt}
**Ärende:** planerat införande av Vault — styrning av det gemensamma AI-minnet

## 1. Grund för förhandlingen
Enligt **11 § MBL** ska arbetsgivaren på eget initiativ förhandla med den kollektivavtalsbundna organisationen innan
beslut fattas om **viktigare förändring av verksamheten** eller av arbets- eller anställningsförhållandena.
Införandet av ett system som behandlar personuppgifter om arbetstagare utgör en sådan förändring.

Arbetsgivaren fattar inget beslut och vidtar ingen åtgärd innan förhandlingen är avslutad.

## 2. Information enligt 19 § MBL
| Fråga | Svar |
|---|---|
| Vad registreras | Interaktioner med företagets AI-system, ${settings.sampleDontStream ? `stickprovsvis (${Math.round((settings.sampleRate ?? 0.05) * 100)} %)` : 'löpande'} |
| Vad registreras inte | ${list(settings.excludedContexts)} |
| Tidsfönster | ${settings.workingHoursOnly ? 'endast under arbetstid' : 'ingen tidsbegränsning'} |
| Pseudonymisering | ${settings.pseudonymiseByDefault ? 'ja, som standard' : 'nej'} |
| Minsta gruppstorlek vid analys | k = ${settings.kAnonymityFloor ?? 5} |
| Individuell uppföljning | ${settings.noIndividualDashboards ? 'finns inte i systemet' : 'finns'} |
| Gallring | ${settings.employeeRetention ?? 'standardtid'} |
| Rättslig grund | Artikel 6.1 f GDPR, berättigat intresse, med dokumenterad intresseavvägning |

## 3. Syfte
AI-agenter läser från och skriver till ett gemensamt minne. Utan kontroll kan vilket innehåll som helst bli ett
bestående "faktum" som andra system litar på. Vault prövar varje kandidat innan den får bli ett minne, och registrerar
vad som troddes och när.

## 4. Vad systemet uttryckligen inte gör
Prestations- eller produktivitetsmätning · emotions-, stämnings- eller engagemangsanalys (även förbjudet enligt
artikel 5.1 f i AI-förordningen) · dold övervakning · underlag för arbetsrättsliga åtgärder · individuella
instrumentpaneler, inte heller för HR och inte heller via nödåtkomst.

## 5. Arbetstagarnas rättigheter
Registerutdrag, export, rättelse och formell invändning via portalen "Mina uppgifter". IMY:s vägledning om
arbetsgivares kontrollåtgärder har följts vid utformningen.

## 6. Fackets insyn
Facket erbjuds en egen läsbehörighet till konfiguration, gallringstider, behörighetsmatris och samtliga
åter-identifieringar. Ändringar i övervakningsrelevanta inställningar föranleder ny förhandling enligt 11 § MBL.

## 7. Förslag till förhandlingsordning
| Steg | Tid |
|---|---|
| Lokal förhandling | [datum] |
| Eventuell central förhandling (14 § MBL) | inom [x] veckor om oenighet kvarstår |
| Beslut | tidigast efter avslutad förhandling |
| Uppföljning | 6 och 12 månader efter införandet |

## 8. Bilagor
1. Konsekvensbedömning enligt artikel 35 GDPR
2. Intresseavvägning (artikel 6.1 f)
3. Behörighetsmatris
4. Personuppgiftsbiträdesavtal${SE_DISCLAIMER}`;
}

export function seIntresseavvagning({ settings, generatedAt }) {
  return `# Intresseavvägning enligt artikel 6.1 f GDPR
**Datum:** ${generatedAt} · **Personuppgiftsansvarig:** [arbetsgivare]

## 1. Ändamålstest
Det berättigade intresset är riktigheten och säkerheten i företagets gemensamma AI-minne, samt möjligheten att i
efterhand visa vad ett AI-system trodde vid en viss tidpunkt. Detta är ett verkligt och aktuellt intresse: manipulerade
minnen har dokumenterat använts för att styra automatiserade beslut.

## 2. Nödvändighetstest
Mindre ingripande alternativ har prövats och avvisats: enbart loggning utan prövning förhindrar inte att felaktigt
innehåll blir ett bestående faktum, och enbart instruktioner till medarbetare skyddar inte mot innehåll som kommer
utifrån. Behandlingen är därmed nödvändig för ändamålet.

## 3. Avvägningstest
Behandlingen är begränsad till ${settings.sampleDontStream ? 'stickprov' : 'fullständig registrering'} av interaktioner
med företagets AI-system. Uppgifterna pseudonymiseras${settings.pseudonymiseByDefault ? ' som standard' : ' inte'},
analyser sker endast aggregerat med k = ${settings.kAnonymityFloor ?? 5}, och
${list(settings.excludedContexts)} registreras inte alls. Gallring sker efter
${settings.employeeRetention ?? 'standardtid'}. Individuell prestationsuppföljning saknas i systemet.

**Slutsats:** de registrerades intressen och grundläggande rättigheter väger inte tyngre än det berättigade intresset,
förutsatt att ovanstående begränsningar upprätthålls. Avvägningen omprövas vid varje ändring av inställningarna.${SE_DISCLAIMER}`;
}

// ---------------------------------------------------------------------------
// 🇫🇷 FRANCE — CSE consultation (L2312-8 / L2312-38) + CNIL
//
// France stacks three separate obligations that are easy to conflate: the CSE
// must be *consulted* (with a one-month default deadline that starts when the
// information is complete), employees must be *individually informed*
// (L1222-4 — anything not disclosed cannot be used against them), and the
// processing must go in the *registre des traitements*. Missing the individual
// information step is the one that gets evidence thrown out at the prud'hommes,
// so it gets its own document below.
// ---------------------------------------------------------------------------

export function frCseConsultation({ settings, generatedAt }) {
  return `# Note d'information et de consultation du CSE
**Destinataire :** Comité social et économique · **Émetteur :** la direction · **Date :** ${generatedAt}
**Objet :** projet d'introduction de Vault — gouvernance de la mémoire partagée des systèmes d'IA

## 1. Fondement de la consultation
Articles **L. 2312-8** (consultation sur l'introduction de nouvelles technologies et sur tout aménagement important
modifiant les conditions de travail) et **L. 2312-38** (moyens ou techniques permettant un contrôle de l'activité des
salariés) du code du travail.

Conformément à l'article R. 2312-6, le CSE dispose d'un délai d'**un mois** à compter de la mise à disposition
d'informations complètes pour rendre son avis, porté à deux mois en cas de recours à un expert. Aucune mise en service
n'interviendra avant l'expiration de ce délai ou la remise de l'avis.

## 2. Objet du dispositif
Les agents d'IA lisent et écrivent dans une mémoire partagée. Sans contrôle, tout contenu rencontré par un agent — y
compris un courriel externe ou une injection de consigne — peut devenir un « fait » durable auquel d'autres systèmes
se fieront. Vault évalue chaque contenu candidat avant mémorisation et conserve la trace de ce qui était tenu pour
vrai, et quand.

## 3. Conséquences sur les conditions de travail
| Élément | Paramétrage retenu |
|---|---|
| Données collectées | interactions avec les systèmes d'IA de l'entreprise, ${settings.sampleDontStream ? `par échantillonnage (${Math.round((settings.sampleRate ?? 0.05) * 100)} %)` : 'en continu'} |
| Exclusions | ${list(settings.excludedContexts)} |
| Plage horaire | ${settings.workingHoursOnly ? 'temps de travail effectif uniquement — droit à la déconnexion (L. 2242-17) respecté' : 'sans limitation horaire'} |
| Pseudonymisation | ${settings.pseudonymiseByDefault ? 'par défaut' : 'non activée'} |
| Restitutions individuelles | ${settings.noIndividualDashboards ? 'inexistantes dans le produit' : 'disponibles'} |
| Seuil d'agrégation | k = ${settings.kAnonymityFloor ?? 5} |
| Durée de conservation | ${settings.employeeRetention ?? 'durée standard'} |
| Base légale | article 6.1.f RGPD, intérêt légitime, avec analyse documentée |

## 4. Ce que le dispositif ne permet pas
Évaluation de la performance ou de la productivité · analyse des émotions, de l'humeur, du stress ou de l'engagement
(également interdite par l'article 5.1.f du règlement européen sur l'IA) · surveillance clandestine · fondement d'une
mesure disciplinaire · tableaux de bord individuels, y compris pour la DRH et y compris par accès d'urgence.

## 5. Proportionnalité (article L. 1121-1 et doctrine CNIL)
La direction atteste que le dispositif est **justifié par la nature de la tâche et proportionné au but recherché** :
la surveillance permanente et individualisée est écartée ; l'échantillonnage est préféré au flux continu ; les données
sont pseudonymisées ; les contextes personnels sont exclus par construction.

## 6. Information individuelle des salariés (L. 1222-4)
Une note individuelle est remise à chaque salarié avant la mise en service. **Aucune information collectée à l'insu du
salarié ne peut lui être opposée.** Le modèle figure en annexe 2.

## 7. Formalités RGPD
Inscription au **registre des traitements** (article 30 RGPD) · AIPD au titre de l'article 35 · désignation du DPO ·
contrat de sous-traitance conforme à l'article 28.

## 8. Calendrier proposé
| Étape | Échéance |
|---|---|
| Remise du dossier complet au CSE | ${generatedAt} |
| Réunion de présentation | sous 15 jours |
| Avis du CSE | dans le délai d'un mois (deux mois avec expert) |
| Information individuelle des salariés | avant toute mise en service |
| Bilan présenté au CSE | à 6 et 12 mois |

## Annexes
1. AIPD (article 35 RGPD) générée depuis la configuration active
2. Modèle de note d'information individuelle
3. Matrice des habilitations
4. Contrat de sous-traitance${FR_DISCLAIMER}`;
}

export function frNoteIndividuelle({ settings, generatedAt }) {
  return `# Note d'information individuelle aux salariés (article L. 1222-4 du code du travail)
**Date d'effet :** ${generatedAt}

Madame, Monsieur,

L'entreprise met en place **Vault**, un dispositif de gouvernance de la mémoire partagée de ses systèmes d'intelligence
artificielle. Conformément à l'article L. 1222-4 du code du travail, vous êtes informé(e) individuellement de son
existence avant sa mise en service.

**Ce qui est enregistré.** Les interactions avec les systèmes d'IA de l'entreprise,
${settings.sampleDontStream ? 'par échantillonnage et sur événement' : 'en continu'},
${settings.workingHoursOnly ? 'pendant le temps de travail uniquement' : 'sans limitation horaire'}.

**Ce qui n'est jamais enregistré.** ${list(settings.excludedContexts)}.

**Ce à quoi cela ne sert pas.** Le dispositif n'évalue ni votre performance, ni votre productivité, ni votre état
émotionnel. Ces fonctions n'existent pas dans le produit : il ne s'agit pas d'un paramètre désactivé.

**Vos droits.** Vous pouvez consulter les données vous concernant, les exporter, en demander la rectification et former
une **contestation** via le portail « Mes données ». Vos droits au titre des articles 15 à 22 du RGPD s'exercent auprès
du DPO : [contact]. Vous pouvez également saisir la CNIL.

**Durée de conservation.** ${settings.employeeRetention ?? 'durée standard'}.

**Consultation du CSE.** Le comité social et économique a été consulté le [date] et son avis est consultable auprès de
[service].${FR_DISCLAIMER}`;
}

// ---------------------------------------------------------------------------
// 🇮🇳 INDIA — employee monitoring
//
// India has no dedicated employee-monitoring statute, and the honest thing is
// to say so rather than invent one. What it does have: the DPDP Act 2023 (with
// a notably broad employment exemption at §7(i) that people over-read), the IT
// Act §43A / SPDI Rules 2011 for sensitive personal data, §72A for wrongful
// disclosure, state Shops & Establishments Acts, and — the one that actually
// bites — the constitutional privacy right from Puttaswamy, which reaches
// private employers indirectly through the courts' reading of contracts and
// service rules. This document maps each of those to what Vault does.
// ---------------------------------------------------------------------------

export function inEmployeeMonitoringPosition({ settings, generatedAt }) {
  return `# Employee monitoring in India — legal position and Vault's configuration
**Generated:** ${generatedAt}

## 1. The honest starting point
**India has no dedicated employee-monitoring statute.** There is no Indian equivalent of §87 BetrVG, Article 27 WOR or
Ontario's ESA s. 41.1.1. Anyone who tells you there is a single "India employee monitoring law" to comply with is
wrong. What exists instead is a stack of five instruments, each covering part of the ground.

## 2. The five instruments that actually apply

### 2.1 Digital Personal Data Protection Act, 2023
Applies to employee personal data. The Act's **§ 7(i)** permits processing "for the purposes of employment or those
related to safeguarding the employer from loss or liability, such as prevention of corporate espionage, maintenance of
confidentiality of trade secrets, intellectual property, classified information or provision of any service or benefit
sought by a Data Principal who is an employee" — **without consent**, as a legitimate use.

This exemption is broader than the GDPR equivalent and is frequently over-read. Three limits survive it:
- **§ 8(4)–(5) still apply:** accuracy obligations and reasonable security safeguards are not waived.
- **§ 5 notice still applies** for processing outside the legitimate-use ground, and giving notice anyway is the
  defensible position — the exemption removes the consent requirement, not the transparency expectation.
- **§ 8(7) storage limitation** and the erasure duty still apply.

**Vault's position:** the legitimate-use ground under § 7(i) is available and is what this pack relies on, but Vault
issues an employee notice regardless, because a monitoring programme that relies on an exemption to avoid telling
people about it is the programme that loses at the tribunal.

### 2.2 Information Technology Act, 2000 — § 43A and the SPDI Rules, 2011
Sensitive personal data or information (passwords, financial information, health, biometrics, sexual orientation,
medical records) attracts the SPDI Rules: a published privacy policy, consent for collection, purpose limitation,
disclosure restrictions, and **reasonable security practices** (the Rules name ISO/IEC 27001 as one accepted standard).
§ 43A creates civil liability for negligent handling causing wrongful loss.
**§ 72A** creates criminal liability for disclosure of personal information in breach of a lawful contract.

**Vault's position:** categories in the SPDI list are detected and masked before they can become durable facts;
${settings.pseudonymiseByDefault ? 'employee identifiers are pseudonymised by default' : 'pseudonymisation is currently OFF — reconsider'};
encryption at rest and in transit, role-based access and the tamper-evident ledger are the "reasonable security
practices" evidence.

### 2.3 The constitutional privacy right — *K.S. Puttaswamy v. Union of India* (2017) 10 SCC 1
Privacy is a fundamental right under Article 21. It binds the State directly, and reaches private employers indirectly:
Indian courts read employment contracts, service rules and disciplinary proceedings against it, and apply the
proportionality test (legitimate aim · rational nexus · necessity · balancing) when monitoring is challenged.

**Vault's position:** the proportionality analysis is generated as a document, not assumed — see § 4 below.

### 2.4 State Shops and Establishments Acts, and the Industrial Employment (Standing Orders) Act, 1946
Monitoring that affects conditions of service generally must be reflected in **certified standing orders** for
establishments covered by the 1946 Act, and in the employee handbook elsewhere. Several states additionally require
notice of surveillance in the workplace.
**Vault's position:** a standing-orders clause is provided below for insertion by counsel.

### 2.5 Sector rules
RBI (banking and payments), SEBI (securities), IRDAI (insurance) and TRAI each impose their own record-keeping,
localisation and audit expectations that can be *stricter* than DPDP. Where a sector pack is enabled, it layers on top.

## 3. What Vault is configured to do here
| Setting | Value |
|---|---|
| Notice to employees | issued, despite the § 7(i) exemption |
| Data collected | interactions with company AI systems, ${settings.sampleDontStream ? `sampled (${Math.round((settings.sampleRate ?? 0.05) * 100)}%)` : 'continuous'} |
| Never collected | ${list(settings.excludedContexts)} |
| Working-hours limit | ${settings.workingHoursOnly ? 'yes' : 'no'} |
| Pseudonymisation | ${settings.pseudonymiseByDefault ? 'default on' : 'off'} |
| Individual dashboards | ${settings.noIndividualDashboards ? 'do not exist in the product' : 'available'} |
| Aggregation floor | k = ${settings.kAnonymityFloor ?? 5} |
| Employee data retention | ${settings.employeeRetention ?? 'standard'} |
| Security log retention | 1 year (DPDP Rules) |
| Consent records retention | 7 years |
| Grievance redressal | named officer, published contact, tracked response — DPDP § 13 |

## 4. Proportionality analysis (Puttaswamy test)
**Legitimate aim.** Integrity of the shared AI memory; prevention of loss and liability arising from poisoned or
fabricated facts — squarely within § 7(i)'s "safeguarding the employer from loss or liability".
**Rational nexus.** Screening content before it becomes a durable fact is directly connected to that aim.
**Necessity.** Logging without screening records the harm after it occurs; instruction alone does not reach content
arriving from outside the organisation. Neither achieves the aim.
**Balancing.** ${settings.sampleDontStream ? 'Sampling rather than continuous capture' : 'Continuous capture'};
pseudonymisation${settings.pseudonymiseByDefault ? ' by default' : ' disabled'}; exclusion of
${list(settings.excludedContexts)}; no individual performance visibility; deletion after
${settings.employeeRetention ?? 'the standard period'}.

## 5. Standing-orders clause (for counsel to adapt)
> **Use of company artificial-intelligence systems.** The establishment operates governance controls over the shared
> memory of its artificial-intelligence systems. Interactions with those systems are recorded for the purposes of
> accuracy, security and statutory record-keeping. Such records are **not** used to assess the performance, productivity
> or conduct of any workman, and the system provides no capability to do so. ${settings.excludedContexts?.length ? `Personal accounts, personal devices, union communications and the other contexts listed in the employee notice are excluded from recording.` : ''}
> Workmen may inspect the data held about them, seek correction, and raise a grievance with the Data Protection Officer
> under the establishment's grievance-redressal procedure.

## 6. What this document does not cover
Employment-law questions outside data protection (termination, disciplinary procedure, industrial disputes);
CCTV and physical-premises surveillance; call-recording under TRAI rules; cross-border transfer restrictions notified
under DPDP § 16, which are issued by the Central Government by notification and change without much notice.

## 7. Milestones being tracked
- **DPDP Rules** — phased commencement; consent-manager registration and the notice format take effect on the dates
  set in the Rules as notified.
- **Significant Data Fiduciary designation** — if designated, annual DPIA, independent audit and an India-resident DPO
  become mandatory. Vault generates the DPIA and the audit evidence pack.
- **Penalty exposure** — up to ₹250 crore per contravention for failure to take reasonable security safeguards; this is
  surfaced on the board pack rather than buried in a settings screen.${EN_DISCLAIMER}`;
}

export function inEmployeeNotice({ settings, generatedAt }) {
  return `# Notice to employees — governance of company AI systems
**Effective:** ${generatedAt} · **Data Fiduciary:** [Company] · **Data Protection Officer:** [name, India-resident]

We use a system called Vault to govern what our AI systems are allowed to remember. This notice tells you what that
means for you. We are giving you this notice even though § 7(i) of the Digital Personal Data Protection Act, 2023
permits this processing without your consent, because you should know either way.

**What is recorded.** Your interactions with company AI systems,
${settings.sampleDontStream ? 'sampled rather than streamed continuously' : 'continuously'},
${settings.workingHoursOnly ? 'during working hours only' : 'without a time restriction'}.

**What is never recorded.** ${list(settings.excludedContexts)}.

**Why.** So that a fabricated or manipulated statement cannot become something the company's AI systems treat as true,
and so that we can show afterwards what was believed and when.

**What it is not used for.** Not your performance. Not your productivity. Not your mood, stress or engagement. Those
capabilities are absent from the product — this is not a switch that is currently off.

**How long.** ${settings.employeeRetention ?? 'The standard retention period'} for employee-linked data; one year for
security logs; seven years for consent records.

**Your rights under the DPDP Act.** Access to a summary of your personal data (§ 11), correction and erasure (§ 12),
grievance redressal (§ 13), and nomination (§ 14). Use the "My Data" portal, or contact the Data Protection Officer at
[contact]. If unsatisfied, you may complain to the Data Protection Board of India.

**Sharing.** Your data is not sold, and is not shared outside the company except as required by law.${EN_DISCLAIMER}`;
}

export const CODETERMINATION_DOCS = {
  at: [
    { name: 'Betriebsvereinbarung (AT, § 96 Abs. 1 Z 3 ArbVG) — Entwurf', format: 'markdown', body: atBetriebsvereinbarung },
    { name: 'Datenschutzrechtliche Beurteilung (DSG/DSGVO)', format: 'markdown', body: atDsgAssessment }
  ],
  nl: [
    { name: 'Instemmingsverzoek ex artikel 27 WOR', format: 'markdown', body: nlInstemmingsverzoek },
    { name: 'DPIA-addendum — proportionaliteit en subsidiariteit (AP)', format: 'markdown', body: nlDpiaAddendum }
  ],
  se: [
    { name: 'Kallelse till förhandling enligt 11 § MBL', format: 'markdown', body: seMblForhandling },
    { name: 'Intresseavvägning (artikel 6.1 f GDPR)', format: 'markdown', body: seIntresseavvagning }
  ],
  fr: [
    { name: 'Note d\'information et de consultation du CSE', format: 'markdown', body: frCseConsultation },
    { name: 'Note d\'information individuelle (L. 1222-4)', format: 'markdown', body: frNoteIndividuelle }
  ],
  in: [
    { name: 'Employee monitoring in India — legal position', format: 'markdown', body: inEmployeeMonitoringPosition },
    { name: 'Notice to employees (DPDP)', format: 'markdown', body: inEmployeeNotice }
  ]
};
